import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import Layout from "@/components/Layout";
import Login from "@/components/Login";
import ReduxProvider from "@/state/ReduxProvider";

import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "INDX Admin",
  description: "Generated by create next app",
  icons: {
    icon: ["/assets/images/favicon/favicon.ico"],
    apple: ["/assets/images/favicon/apple-touch-icon.png"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const userToken = cookieStore.get("user")?.value;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          {userToken ? <Layout>{children}</Layout> : <Login />}
        </ReduxProvider>
      </body>
    </html>
  );
}
